const $=s=>document.querySelector(s); const historyKey="linkforge-history";
const state={origin:sessionStorage.getItem("linkforge-origin")||"http://localhost:8787",key:sessionStorage.getItem("linkforge-key")||""};
function renderHistory(){const items=JSON.parse(localStorage.getItem(historyKey)||"[]"); $("#history").innerHTML=items.length?items.map(x=>`<li><strong>${escapeHtml(x.source)}</strong><br><small>${escapeHtml(x.id)} · ${escapeHtml(x.status)}</small></li>`).join(""):"<li>No local captures yet.</li>"}
function escapeHtml(v){const d=document.createElement("div");d.textContent=v;return d.innerHTML}
async function request(path,options={}){const r=await fetch(state.origin+path,{...options,headers:{"Content-Type":"application/json","Authorization":`Bearer ${state.key}`,...options.headers}});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.json()}
async function poll(id,source){const el=$("#status"); for(let i=0;i<90;i++){const job=await request(`/v1/captures/${id}`);el.innerHTML=`<strong>${escapeHtml(job.status)}</strong><p>${escapeHtml(source)}</p>`;if(job.status==="complete"){el.innerHTML+=`<ul>${job.artifacts.map(a=>`<li><a href="${state.origin}/v1/captures/${id}/artifacts/${encodeURIComponent(a)}" target="_blank" rel="noreferrer">${escapeHtml(a)}</a></li>`).join("")}</ul>`;saveHistory({id,source,status:job.status});return}if(job.status==="failed")throw new Error(job.error||"Capture failed");await new Promise(r=>setTimeout(r,2000))}throw new Error("Capture timed out")}
function saveHistory(item){const items=JSON.parse(localStorage.getItem(historyKey)||"[]").filter(x=>x.id!==item.id);localStorage.setItem(historyKey,JSON.stringify([item,...items].slice(0,20)));renderHistory()}
$("#captureForm").addEventListener("submit",async e=>{e.preventDefault();const source=$("#source").value;const provider=new FormData(e.currentTarget).get("provider");const status=$("#status");status.hidden=false;status.textContent="Submitting capture…";try{if(!state.key)throw new Error("Set an API key first.");const job=await request("/v1/captures",{method:"POST",body:JSON.stringify({source,provider})});saveHistory({id:job.id,source,status:job.status});await poll(job.id,source)}catch(err){status.textContent=`Error: ${err.message}`}});
$("#settingsButton").onclick=()=>{$("#apiOrigin").value=state.origin;$("#apiKey").value=state.key;$("#settings").showModal()};
$("#saveSettings").onclick=()=>{state.origin=$("#apiOrigin").value.replace(/\/$/,"");state.key=$("#apiKey").value;sessionStorage.setItem("linkforge-origin",state.origin);sessionStorage.setItem("linkforge-key",state.key)};
$("#clearHistory").onclick=()=>{localStorage.removeItem(historyKey);renderHistory()};
renderHistory(); if("serviceWorker" in navigator)navigator.serviceWorker.register("sw.js");
